### ISSUE TITLE
cannot find role

### ISSUE THREAD

**Issue by geier** [sean-/freebsd-laptops#1]
I'm not sure if I'm not doing this correctly (never used ansible before), but when I run `make plan` I get this error:

```
$ make plan
ansible-playbook -s site.yml -e @config.yml --check
ERROR: cannot find role in /usr/home/cg/workspace/freebsd-laptops/roles/opensmtpd or /usr/home/cg/workspace/freebsd-laptops/opensmtpd or /usr/local/etc/ansible/roles/opensmtpd
```

**Comment by sean-** [comment]
Should be fixed in the most recent commit (I accidentally leaked an OpenSMTPD commit in which didn't have the accompanying role).
